CREATE TABLE net_activities (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    duration TEXT NOT NULL,
    grouping TEXT NOT NULL,
    category_id INTEGER REFERENCES net_categories(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER REFERENCES net_users(id) NOT NULL
);