INSERT INTO net_savedlessons (user_id, title, date, day, classlevel, period, topic, goal, class_size, 
                            objective_one, objective_two, objective_three, materials, warmup_id, 
                            presentation_one_id, presentation_two_id, practice_one_id, practice_two_id,
                            practice_three_id, product_one_id, product_two_id, cooldown_id, reflection_one, reflection_two,
                            reflection_three)
VALUES (
    1,
    'Sample Lesson Plan (Some inputs filled)',
    '2020/02/10',
    'Wednesday',
    'Junior High 1st Year',
    'Period 03',
    'I can ...',
    'The goal of the lesson is for student to be able to use I can ~',
    23,
    'Use I can to describe things they can do.',
    NULL,
    NULL,
    'Textbook,Worksheets,Props',
    6,
    11,
    2,
    16,
    19,
    NULL,
    21,
    NULL,
    30,
    'Did the students enjoy the lesson?',
    'Did the studnets understand how to use I can?',
    NULL);