BEGIN;


    INSERT INTO net_users( username, email, password )
VALUES
    ('admin', 'admin@admin', '$2a$12$jYBgjmooGLO5NWg8L.SBO.h1eU.6HCfhFHPf8uww9Zy2uySNNa3mG'),
    ('dunder', 'Dunder@gmail.com', '$2a$12$lHK6LVpc15/ZROZcKU00QeiD.RyYq5dVlV/9m4kKYbGibkRc5l4Ne'),
    ('b.deboop', 'Bodeep@gmail.comp', '$2a$12$VQ5HgWm34QQK2rJyLc0lmu59cy2jcZiV6U1.bE8rBBnC9VxDf/YQO'),
    ('c.bloggs', 'Charlie@gmail.com', '$2a$12$2fv9OPgM07xGnhDbyL6xsuAeQjAYpZx/3V2dnu0XNIR27gTeiK2gK'),
    ('s.smith', 'Sam@gmail.com', '$2a$12$/4P5/ylaB7qur/McgrEKwuCy.3JZ6W.cRtqxiJsYCdhr89V4Z3rp.'),
    ('lexlor', 'Alex@gmail.com', '$2a$12$Hq9pfcWWvnzZ8x8HqJotveRHLD13ceS7DDbrs18LpK6rfj4iftNw.'),
    ('wippy', 'Ping@gmail.com', '$2a$12$ntGOlTLG5nEXYgDVqk4bPejBoJP65HfH2JEMc1JBpXaVjXo5RsTUu');
    
INSERT INTO net_categories ( title )
VALUES
    ('Warmup'),
    ('Presentation'),
    ('Practice'),
    ('Production'),
    ('Cooldown');

INSERT INTO net_activities (title, content, category_id, duration, grouping, user_id)
VALUES
    ('Choose a Warm-up Activity',
    ' ',
    1,
    ' ',
    ' ',
    1),
    ('Choose a Presentation Activity',
    ' ',
    2,
    ' ',
    ' ',
    1),
    ('Choose a Practice Activity',
    ' ',
    3,
    ' ',
    ' ',
    1),
    ('Choose a Production Activity',
    ' ',
    4,
    ' ',
    ' ',
    1),
    ('Choose a Cooldown Activity',
    ' ',
    5,
    ' ',
    ' ',
    1),
    ('Blank Warmup',
    '_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________',
    1,
    '____________________',
    '____________________',
    1),
    ('Blank Presentation',
    '_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________',
    2,
    '____________________',
    '____________________',
    1),
    ('Blank Practice',
    '_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________',
    3,
    '____________________',
    '____________________',
    1),
    ('Blank Performance',
    '_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________',
    4,
    '____________________',
    '____________________',
    1),
    ('Blank Cooldown',
    '_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________\n \r_________________________________________________________________________',
    5,
    '____________________',
    '____________________',
    1),
    ('Teachers''s Day',
    'Write an essay about your life using known grammar forms and/or target grammar forms.\n \rIf you use unfamiliar vocabulary, provide Japanese translations (ask your JTE for help).\n \rChoose 5-10 words and change them into blanks.\n \rThe ALT reads his/her essay 2-3 times.\n \rThe students listen and try to fill in the blanks by catching the sound.\n \rAfter the ALT has finished reading, the JTE reads the essay one more time, pausing before each blank.\n \rThe class says the correct answer in unison.\n \rThe ALT writes the correct spelling on the board.',
    1,
    '5min',
    'Individual',
    1),
    ('Make the most words',
    'Write a topical vocabulary item on the board.\n \rIn pairs, students make as many new words from it as they can.\n \rUse longish seed words such as ''apologise'', ''dictionary'' or ''September''.\n \rScore teams a point per word and award a bonus point for the longest.',
    1, 
    '5min', 
    'Pairs', 
    1),
    ('Hangman', 
    'Just put a recently learned word on the board using dashes only.\n \rLet the students take it in turns to guess a letter.',
    1, 
    '10min', 
    'Whole Class', 
    1),
    ('Word ladders', 
    'In this activity, a word must be transformed step by step into a target word.\n \rTo illustrate the idea, write the word run on the board and explain that the target word is fit.\n \rFor each turn, only one letter can be changed.\n \rSee if the class can find a valid sequence together.\n \rFor example run -> fun -> fin -> fit.\n \rGo to https://www.keithschwarz.com/interesting/code/word-ladder/WordLadders.html to help with word ladders you can use.',
    1,
    '10min',
    'Pairs',
    1),
    ('The A to Z game',
    'Give students a theme, for example, ''jobs'', ''things you take on holiday'', ''food''.\n \rWrite the letters A to Z on the board.\n \rTeams of students must race to write an appropriate word next to each letter on the board.',
    1,
    '10min',
    'Groups',
    1),
    ('Skit',
    'Write a script that uses the grammar focus for the students.\n \rWith the Teacher perform the skit, putting focus on the grammar and vocabulary the students will be learning that day.\n \r. Then get some students to peform your skit, letting them see if they can understand how to use the grammar point.\n \rAfter, explain how the grammar works.',
    2,
    '10min',
    'Individual',
    1),
    ('Guess the Meaning',
    'Have a list of all the words that the students will be using for the lesson cut up on one side of the board.\n \rOn the other side of the board, have a list of the meanings of the words.\n \rThe students try to guess the meaning of the vacabulary words and give a reason why they think it is correct.\n \rWhen everything is settled, reveal the answers to the students.',
    2,
    '10min',
    'Whole Class',
    1),
    ('Garden Path',
    'Explain to the stundents a very quick explaination of how to use a certain grammar point.\n \rPrepare examples and ask students to apply the grammar point to the example by calling it out.\n \rAdd in something that does not follow the rule but is still on the grammar topic.\n \rFor example, all regular past tense words, and then an irregular past tense word.\n \rGive an explaination of the different rules.',
    2,
    '10min',
    'Whole Class',
    1),
    ('Fill in the blanks',
    'Find song that heavily uses the target vocabulary.\n \rPrepare a worksheet of the lyrics where you remove the target vocabulary, along with some that the students know.\n \rHand out the worksheet, and have studnets guess which word fills the blanks.\n \rHave them listen to the song and check their answers.\n \rCheck answers with the whole class.\n \rGet student to identify the new words that they haven''t seen.\n \rGive them an explaination of the new words.',
    2,
    '10min',
    'Individual',
    1),
    ('What Rules?',
    'On the blackboard write a list of sentences on the board.\n \rRead them out to the studnets, and in pairs have the students write a rule to use the grammar point.\n \rHave the pairs write two or three sentences using their rule.\n \rGo around the class and have students share their rules and their sentences.\n \rWhen all is done, give an explaination of the grammar rule if none of the pairs got it correct, or write down on the board the rule of a pair that got it correct.',
    2,
    '15min',
    'Pairs',
    1),
    ('Worksheets',
    'Give students a worksheets with examples of how to use the grammar point',
    3,
    '5min',
    'Individual',
    1),
    ('Shadowing Your Friend',
    'Give studnes each a passage to read that heavily uses the grammar point or the vocabulary.\n \rLet them practice it.\n \rWhen they are done, pair the students up with someone that has a different passage.\n \rWhile their partner is reading the passage, have the student that is listening try to say the same thing that their partner is saying.\n \rWhen they have done two passes, switch the speakrs and do it again.',
    3,
    '10min',
    'Pairs',
    1),
    ('Arrange in Order',
    'Create a few dialogues, print them up, and cut them up to individual strips.\n \rMix them up and put them in envelopes.\n \rStudents are to then unscramble the three seperate dialogues.', 
    3, 
    '15min',
    'Groups',
    1),
    ('Change a bit Dialogues',
    'Write a dialoge that uses the grammar point or vocabulary.\n \rThen give studnets some time to create three or four dialogues by changing it to things that know, or have just learnt.\n \rHave students read their dialogues out to the class.', 
    3,
    '10min',
    'Pairs',
    1),
    ('Survey your friends',
    'Using the grammar point have students write down some questions they would like to know about.\n \rHave the studnets walk around the classroom and ask their peers the questions they have written, and to record their answers to the questions.\n \rHave the students tally up the results, and share them with the class.', 
    3,
    '20min',
    'Individual',
    1),
    ('Your Own Role Play',
    'Give the students a topic/theme/scenario.\n \rHave students write a Role play that uses the grammar point of the day',
    4,
    '15min',
    'Pairs',
    1),
    ('Run Out',
    'Split the class into 2 groups.\n \rGive each student an order of when to go.\n \rthe first two students meet in the middle.\n \rThey play rock paper scissors to see who starts. The starting person has 10 seconds to create a question, or a sentence with the vocabulary/grammar point of the day.\n \rStudents cannot say the same sentence twice.\n \rIf a student cannot say a sentence in the allotted time, they go back into line and the next student in the group takes over.\n \rThe winning group is the one that has the most members left over.',
    4,
    '15min',
    'Whole Class',
    1),
    ('Poster Presentation',
    'Students do reasearch on a topic.\n \rThey create a poster of it.\n \rAfter they have created their posters, put them into groups.\n \rHave the students present their posters to the other studnets.\n \rAfter the presentation is finished, have the audience in the groups ask questions about the presentation.',
    4,
    '15min',
    'Individual',
    1),
    ('Paragraph Writing',
    'Give the students a topic.\n \rHave them write a paragraph on it.',
    4,
    '10min',
    'Individual',
    1),
    ('What happened before/Next?',
    'Read a snippit from a book or Watch a snippit from a T.V show or Movie.\n \rStudents are to write what they thing happened before the snippit, or after the snippit.\n \rHave them share it with the whole class.',
    4,
    '15min',
    'Individual',
    1),
    ('Criss-Cross',
    'Have all the students stand up.\n \rAsk the students a question.\n \rWhen a studnet answers a question, they have a choice of how they want to sit down, by themselves, their row, or their column. Concentrate the questions on the topic of the day.',
    5,
    '5min',
    'Whole Class',
    1),
    ('What is the question?',
    'On the board write down 4 random words.\n \rStudents are to guess the questions that will answer those words. ',
    5,
    '5min',
    'Whole Class',
    1),
    ('Crosswords Worksheet',
    'Create a worksheet with the vocabulary that you have used.',
    5,
    '5min',
    'Individual',
    1),
    ('What have you learned today?',
    'Ask a few of the students to recap the day. ',
    5,
    '5min',
    'Whole Class',
    1),
    ('Performance correction and feedback',
    'Provide students with feedback of how they went duing the lesson. What they did well and what they need to work on. Try not to target individual students.',
    5,
    '5min',
    'Whole Class',
    1);


INSERT INTO net_savedlessons (user_id, title, date, day, classlevel, period, topic, goal, class_size, 
                            objective_one, objective_two, objective_three, materials, warmup_id, 
                            presentation_one_id, presentation_two_id, practice_one_id, practice_two_id,
                            practice_three_id, product_one_id, product_two_id, cooldown_id, reflection_one, reflection_two,
                            reflection_three, duration)
VALUES (
    1,
    'Sample Lesson Plan (Some inputs filled)',
    '2020/02/10',
    'Wednesday',
    'Junior High 1st Year',
    'Period 03',
    'I can ...',
    'The goal of the lesson is for student to be able to use I can ~',
    23,
    'Use I can to describe things they can do.',
    '',
    '',
    'Textbook,Worksheets,Props',
    11,
    16,
    7,
    21,
    24,
    3,
    26,
    4,
    35,
    'Did the students enjoy the lesson?',
    'Did the studnets understand how to use I can?',
    '',
    '50 mins'),
    (
    1,
    'Blank Lesson Plan',
    '2020/02/10',
    'Wednesday',
    'Junior High 1st Year',
    'Period 03',
    'I can ...',
    'The goal of the lesson is for student to be able to ______________________________________',
    40,
    '______________________________________',
    '______________________________________',
    '______________________________________',
    'Textbook,Worksheets,Props',
    6,
    7,
    7,
    8,
    8,
    8,
    9,
    9,
    10,
    '______________________________________',
    '______________________________________',
    '______________________________________',
    '45 mins');

COMMIT;